# Generated by Django 4.2.5 on 2023-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('MX', 'Mexico'), ('US', 'United States'), ('CA', 'Canda'), ('CL', 'Chile'), ('PT', 'Portugal')], max_length=200)),
                ('genre', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('prefiero no decirlo', 'Prefiero no decirlo')], max_length=200)),
            ],
        ),
    ]
